server:
  port: 5000


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3303/db_quarkus
    username: wb-quarkus-usuarios
    password: quarkusdb
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.cj.jdbc.Driver

  #Setando padrao de nome da table para seguir o padrão CamelCase, senao informar ele utilizara a convesao de palavras separadas com underscores
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true




  cache:
    type: redis
    redis:
      time-to-live: 30s

  redis:
    master:
      host: 127.0.0.1
      port: 6379

    slaves:
      - host: 127.0.0.1
        port: 6479